trigger: none
pr: none

variables:
- group: Minecraft

- name: resourceGroupArtifactName
  value: resourceGroup
- name: resourceArtifactName
  value: minecraft

- name: resourceGroupName
  value: minecraft
- name: project
  value: minecraft

stages:
- stage: Build
  displayName: Transpile
  variables:
  - name: workingDirectory
    value: ./bicep
  jobs:
  - job: Transpile
    displayName: Transpile Template
    pool:
      vmImage: $(pipeline#vmImage)
    workspace:
      clean: all
    steps:
    # Resource Group
    - template: /pipeline/templates/bicep.buildandpublish.yaml
      parameters:
        azureResourceManagerConnection: $(pipeline#azure.subscription)
        subscriptionId: $(pipeline#azure.subscription.id)
        location: $(pipeline#azure.location)
        workingDirectory: ${{ variables.workingDirectory }}
        artifactName: ${{ variables.resourceGroupArtifactName }}
        overrideParameters: -resourceGroupName ${{ variables.resourceGroupName }}
                            -location $(pipeline#azure.location)
                            -project ${{ variables.project }}
    # Resources
    - template: /pipeline/templates/bicep.buildandpublish.yaml
      parameters:
        azureResourceManagerConnection: $(pipeline#azure.subscription)
        subscriptionId: $(pipeline#azure.subscription.id)
        resourceGroupName: ${{ variables.resourceGroupName }}
        location: $(pipeline#azure.location)
        workingDirectory: ${{ variables.workingDirectory }}
        artifactName: ${{ variables.resourceArtifactName }}
        overrideParameters: -project ${{ variables.project }}

- stage: Deploy
  displayName: Deployment
  dependsOn: Build
  condition: succeeded()
  variables:
  - name: environment
    value: minecraft
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ variables.environment }}
    pool:
      vmImage: $(pipeline#vmImage)
    strategy:
      runOnce:
        deploy:
          steps:    
          # Resource Group      
          - template: /pipeline/templates/azure.deployment.yaml
            parameters:
              resourceName: Resource Group
              azureResourceManagerConnection: $(pipeline#azure.subscription)
              subscriptionId: $(pipeline#azure.subscription.id)
              location: $(pipeline#azure.location)
              file: $(Pipeline.Workspace)/${{ variables.resourceGroupArtifactName }}/${{ variables.resourceGroupArtifactName }}.json
              parameterFile: $(Pipeline.Workspace)/${{ variables.resourceGroupArtifactName }}/${{ variables.resourceGroupArtifactName }}.parameters.json
              overrideParameters: -resourceGroupName ${{ variables.resourceGroupName }}
                                  -location $(pipeline#azure.location)
                                  -project ${{ variables.project }}
          # Resources      
          - template: /pipeline/templates/azure.deployment.yaml
            parameters:
              resourceName: Resources
              azureResourceManagerConnection: $(pipeline#azure.subscription)
              subscriptionId: $(pipeline#azure.subscription.id)
              resourceGroupName: ${{ variables.resourceGroupName }}
              location: $(pipeline#azure.location)
              file: $(Pipeline.Workspace)/${{ variables.resourceArtifactName }}/${{ variables.resourceArtifactName }}.json
              parameterFile: $(Pipeline.Workspace)/${{ variables.resourceArtifactName }}/${{ variables.resourceArtifactName }}.parameters.json
              overrideParameters: -project ${{ variables.project }}
                                  